### ISSUE TITLE
Song Length > 5:00

### ISSUE THREAD

**Issue by Xyz39808** [digital-sound-antiques/msxplay-js#1]
Player limits song length. Long mml such as https://dl.dropboxusercontent.com/u/39060235/wellbeefington.mus do not play for entire duration. 

Compile to .mgs for full 7:33

**Comment by okaxaki** [comment]
Thank you for your attachment. Currently there's no configuration in the editor page. I should introduce a setting or some meta command line embeded in MML as comment like [shebang](https://en.wikipedia.org/wiki/Shebang_(Unix)).

By the way,  i like the attached song very much. It's that a chiptune I really wanted to listen.

**Comment by okaxaki** [comment]
ATM song length can be specified at the first comment line of MML like:
```
;[duration=300s]
```
