### ISSUE TITLE
Audio playback rate is incorrect after download mp3 from mml editor.

### ISSUE THREAD

**Issue by okaxaki** [digital-sound-antiques/msxplay-js#10]

**Comment by okaxaki** [comment]
This problem was caused MSXPlay and KSS2MP3 instantiate KSSPLAY objects simultaneously. Multiple KSSPLAY objects do not work corretly if the objects have different playback rate. It is a limitation of current OPLL core. All OPLL objects refer the same rate-conversion table.

**Comment by fakazahub** [comment]
I recently download [Cassper Nyovest Any Minute Now Album Download](https://fakazahub.com/albums/album-cassper-nyovest-any-minute-now-zip-file/) it was really good audio playback. Nothing error is come.
