### ISSUE TITLE
Some OPX files play with saturated sound output

### ISSUE THREAD

**Issue by sdsnatcher** [digital-sound-antiques/msxplay-js#11]
Some OPX files are being played with saturated sound output, resulting in a rough sound.

Tested on Safari 13.0.2 and Google Chrome 77.0.3865.120, on mac OS 10.14.6

I attached some of of the problematic files here.

[Problematic_OPX_files.zip](https://github.com/digital-sound-antiques/msxplay-js/files/3748606/Problematic_OPX_files.zip)

**Comment by okaxaki** [comment]
Hi, thank you for reports. I have changed the default gain from 2.0 to 1.0.

**Comment by sdsnatcher** [comment]
Thank you for the fixes!
