### ISSUE TITLE
The song MARCH-1.OPX doesn't produce any sound

### ISSUE THREAD

**Issue by sdsnatcher** [digital-sound-antiques/msxplay-js#13]
The song MARCH-1.OPX supplied at #11 doesn't produce any sound, while on the real MSX the song plays normally.

Tested on Google Chrome 77.0.3865.120, on mac OS 10.14.6.

**Comment by sdsnatcher** [comment]
One approach for this problem could be: From the start of the song, a bigger timer of 10000ms could be set, then reduced to 3000ms only after any sound is produced. What do you think? This should be simple to implement.

**Comment by okaxaki** [comment]
As for use-case on MSXplay.js I agreed, but at this moment, i just patched for this problem.

The silence detection feature is used from application like msxplug to auto-skip empty KSS song track.
So if such bigger timer is directly introduced, it may conflict with this auto-skip feature.
To avoid this,  one better way is  to implement the timer as a default-off new feature to libkss.
However,  i also think MARCH-1.OPX's case is very rare. I'm thinking about where it's worth to implement.
