### ISSUE TITLE
English MGSDRV MML manual

### ISSUE THREAD

**Issue by sdsnatcher** [digital-sound-antiques/msxplay-js#16]
On the bottom-right of the MSXplay.com MML Editor screen there's a link "MML Help" that points to the MGS111.TXT Japanese Manual.

MRC user kumokosi published a preliminary English translation of that manual at [this wiki page](http://mus.msx.click/index.php?title=MGSDRV_MML_11), so it would be nice to also have a link to this English manual on the MML editor.

**Comment by okaxaki** [comment]
Thank you. I have updated the link.
