### ISSUE TITLE
Problematic MuSICA files

### ISSUE THREAD

**Issue by sdsnatcher** [digital-sound-antiques/msxplay-js#2]
There are plenty of MuSICA (.BGM) files in my library that are not being recognised by the demo player.

I attached them here, to help you with the debugging.

[Problematic_MuSICA_files.zip](https://github.com/digital-sound-antiques/msxplay-js/files/2343725/Problematic_MuSICA_files.zip)

**Comment by sdsnatcher** [comment]
Curiously enough, some songs seem to work on Firefox, but not on Safari.

(both running on Mac OS-X 10.13.6)

**Comment by okaxaki** [comment]
Hi, the files in zip are too many for me to reprodce the problem, Could you specify the file which are not being recognized?

**Comment by sdsnatcher** [comment]
None of the files of the BGM01 folder worked here, either on Safari 12.1.1 on Firefox 68.0.1.

The song FINAL_B.BGM played on Firefox, but with distorted sound (volume saturation). On Safari, this song loads, but never plays (pressing the play button changes the symbol, but the playback never starts).

**Comment by okaxaki** [comment]
Sorry for long time to invastigate the problem!!!
The problemactic MuSICA files has header I never seen. I'll fix the check routine if possible.

As for saturation problem, it has been solved  #11.
I noticed recent safari browser cannot play any songs.

**Comment by okaxaki** [comment]
I have fix the problem on songs in BGM01 folder.
