### ISSUE TITLE
Add support for FAC Soundtracker files

### ISSUE THREAD

**Issue by sdsnatcher** [digital-sound-antiques/msxplay-js#6]
Suggestion: Add support for [FAC Soundtracker](https://www.msx.org/wiki/FAC_Soundtracker) files (.MUS extension).

**Comment by okaxaki** [comment]
Since msxplay-js does not aim to the universal music player for msx, so currently there is no plan to support the various file formats which libkss does not support. To play unsupported formats with msxplay-js, please convert them into .kss.
