### ISSUE TITLE
Add support for HAL Music Editor MUE files

### ISSUE THREAD

**Issue by sdsnatcher** [digital-sound-antiques/msxplay-js#7]
Suggestion: Add support for [HAL Music Editor MUE](https://www.generation-msx.nl/software/hal-laboratory/music-editor-mue/342/) files (.MUE).

**Comment by okaxaki** [comment]
Since msxplay-js does not aim to the universal music player for msx, so currently there is no plan to support the various file formats which libkss does not support. To play unsupported formats with msxplay-js, please convert them into .kss.
