### ISSUE TITLE
Add support for SCMD files

### ISSUE THREAD

**Issue by sdsnatcher** [digital-sound-antiques/msxplay-js#8]
Suggestion: Add support for [SCMD](url
http://cpu.dip.jp/3mhz/) files (.SDT).

**Comment by okaxaki** [comment]
Although I'm personally interested in SCMD is very interesting driver, SCMD uses accurate H-SYNC and  interrupt and memory mapper. Unfortunetly underlayering libkss still does not support both.  So currently it is very hard to support SCMD on msxplay-js's current architecture.
