### ISSUE TITLE
Add support for MSX-FAN BGM files

### ISSUE THREAD

**Issue by sdsnatcher** [digital-sound-antiques/msxplay-js#9]
Suggestion: Add support for the MSX-FAN BGM files (.BGM extension).

**Comment by okaxaki** [comment]
msxplay-js can only play KSS data converted from FM-BIOS music.  MSX-FAN's BGM data is a raw FM-BIOS data and it requires FM-BIOS ROM image. Due to the copyright issues, the format cannot be directly supported by msxplay-js.

**Comment by sdsnatcher** [comment]
On a meeting with Nestor (Konamiman) about the Nextor operating system, Nishi has granted that the MSX ROMs can be freely distributed. Check here for the story:

https://www.msx.org/forum/msx-talk/general-discussion/my-meeting-with-kazuhiko-nishi-the-whole-story

**Comment by sdsnatcher** [comment]
Anyway, do you remember the name of that music player for the MSX2 that was capable of playing the MSX-FAN BGM files either on OPLL or MIDI? I only remember that it was published in one of the MSX-Fan disks, but I can't remember its name nor which edition of the MSX-Fan disk it was contained.
